-- ============================================
-- Schema is defined in a single migration.
-- Source of truth: supabase/migrations/20260101000000_initial.sql
--
-- To apply on a fresh project:
--   1. Supabase SQL Editor: copy-paste contents of migrations/20260101000000_initial.sql
--   2. Or use Supabase CLI: supabase db push
-- ============================================
